# Copyright 2024 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG ROS_DISTRO=noetic
ARG FROM=ros:${ROS_DISTRO}-ros-core

FROM ${FROM}

# Must redeclare so that value is available after FROM statement.
ARG ROS_DISTRO

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    python3-rosdep \
    python3-rosinstall \
    python3-vcstools \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Bootstrap rosdep
# Retry because fetching this file from github is unusually flaky
RUN curl -S https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
RUN bash -c 'for i in {1..5}; do rosdep init && break || sleep 15; done'
RUN rosdep update --rosdistro $ROS_DISTRO

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-${ROS_DISTRO}-ros-base \
    && rm -rf /var/lib/apt/lists/*