VERSION 0.8

IMPORT ../apt AS apt
IMPORT ../lib AS lib

rolling:
    ARG image_name='ros'
    ARG registry='localhost/'
    DO +ROS_BINARY_IMAGES \
        --registry=$registry \
        --image_name=$image_name \
        --ROS_DISTRO='rolling' \
        --UBUNTU_IMAGE='ubuntu:noble'


kilted:
    ARG image_name='ros'
    ARG registry='localhost/'
    DO +ROS_BINARY_IMAGES \
        --registry=$registry \
        --image_name=$image_name \
        --ROS_DISTRO='kilted' \
        --UBUNTU_IMAGE='ubuntu:noble'

jazzy:
    ARG image_name='ros'
    ARG registry='localhost/'
    DO +ROS_BINARY_IMAGES \
        --registry=$registry \
        --image_name=$image_name \
        --ROS_DISTRO='jazzy' \
        --UBUNTU_IMAGE='ubuntu:noble'


humble:
    ARG image_name='ros'
    ARG registry='localhost/'
    DO +ROS_BINARY_IMAGES \
        --registry=$registry \
        --image_name=$image_name \
        --ROS_DISTRO='humble' \
        --UBUNTU_IMAGE='ubuntu:jammy'


ROS_BINARY_IMAGES:
    FUNCTION
    ARG --required image_name
    ARG --required registry
    ARG --required ROS_DISTRO
    ARG --required UBUNTU_IMAGE
    ARG use_testing_repo=false

    # ros-core
    FROM --pass-args +ros-core
    DO lib+SAVE_IMAGE_AND_DATE --fully_qualified_name=${registry}${image_name}:${ROS_DISTRO}-ros-core

    # ros-base
    FROM --pass-args +ros-base
    DO lib+SAVE_IMAGE_AND_DATE --fully_qualified_name=${registry}${image_name}:${ROS_DISTRO}-ros-base

    # desktop
    FROM --pass-args +desktop
    DO lib+SAVE_IMAGE_AND_DATE --fully_qualified_name=${registry}${image_name}:${ROS_DISTRO}-desktop

    # perception
    FROM --pass-args +perception
    DO lib+SAVE_IMAGE_AND_DATE --fully_qualified_name=${registry}${image_name}:${ROS_DISTRO}-perception

    # simulation
    FROM --pass-args +simulation
    DO lib+SAVE_IMAGE_AND_DATE --fully_qualified_name=${registry}${image_name}:${ROS_DISTRO}-simulation

    # desktop-full
    FROM --pass-args +desktop-full
    DO lib+SAVE_IMAGE_AND_DATE --fully_qualified_name=${registry}${image_name}:${ROS_DISTRO}-desktop-full


ros-core:
    ARG UBUNTU_IMAGE
    ARG ROS_DISTRO
    ARG use_testing_repo

    FROM $UBUNTU_IMAGE

    # Setup timezone
    RUN echo 'Etc/UTC' > /etc/timezone && \
        ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime

    # Install packages
    DO apt+INSTALL --packages="
        ca-certificates
        curl
        jq
        lsb-release"

    # Setup keys and apt sources
    RUN set -eux; \
        export ROS_APT_SOURCE_VERSION=$(curl --retry 5 -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | jq -r ".tag_name"); \
        if [ "${use_testing_repo}" = "true" ]; then \
            curl --retry 5 -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-testing-apt-source_${ROS_APT_SOURCE_VERSION}.$(lsb_release -sc)_all.deb"; \
        else \
            curl --retry 5 -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(lsb_release -sc)_all.deb"; \
        fi ; \
        apt install /tmp/ros2-apt-source.deb; \
        rm /tmp/ros2-apt-source.deb

    # Setup environment
    ENV LANG C.UTF-8
    ENV LC_ALL C.UTF-8

    ENV ROS_DISTRO ${ROS_DISTRO}

    # Install ROS packages
    DO apt+INSTALL --packages=ros-${ROS_DISTRO}-ros-core

    # Setup entrypoint
    COPY ./ros_entrypoint.sh /

    ENTRYPOINT ["/ros_entrypoint.sh"]
    CMD ["bash"]

    SAVE IMAGE localhost/ros-intermediate:${ROS_DISTRO}-ros-core


ros-base:
    ARG ROS_DISTRO

    FROM --pass-args +ros-core

    # Install bootstrap tools
    DO apt+INSTALL --packages="
        build-essential
        git
        python3-colcon-common-extensions
        python3-colcon-mixin
        python3-rosdep
        python3-vcstool"

    # Bootstrap rosdep
    RUN rosdep init && \
        rosdep update --rosdistro $ROS_DISTRO

    # Setup colcon mixin and metadata
    RUN colcon mixin add default \
        https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
        colcon mixin update && \
        colcon metadata add default \
        https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml && \
        colcon metadata update

    # Install ROS packages
    DO apt+INSTALL --packages=ros-${ROS_DISTRO}-ros-base

    SAVE IMAGE localhost/ros-intermediate:${ROS_DISTRO}-ros-base


desktop:
    ARG ROS_DISTRO
    FROM --pass-args +ros-base
    DO apt+INSTALL --packages=ros-${ROS_DISTRO}-desktop
    SAVE IMAGE localhost/ros-intermediate:${ROS_DISTRO}-desktop


perception:
    ARG ROS_DISTRO
    FROM --pass-args +ros-base
    DO apt+INSTALL --packages=ros-${ROS_DISTRO}-perception
    SAVE IMAGE localhost/ros-intermediate:${ROS_DISTRO}-perception


simulation:
    ARG ROS_DISTRO
    FROM --pass-args +ros-base
    DO apt+INSTALL --packages=ros-${ROS_DISTRO}-simulation
    SAVE IMAGE localhost/ros-intermediate:${ROS_DISTRO}-simulation


desktop-full:
    ARG ROS_DISTRO
    FROM --pass-args +desktop
    DO apt+INSTALL --packages=ros-${ROS_DISTRO}-desktop-full
    SAVE IMAGE localhost/ros-intermediate:${ROS_DISTRO}-desktop-full
