name: Build and Deploy ros-testing

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *'  # 00:00 every day.

permissions:
      packages: write
      contents: read

jobs:

  call-build-and-deploy-jazzy:
    uses: ./.github/workflows/build-and-deploy-one-ros-distro-testing.yaml
    with:
      ros_distro: jazzy
