name: Build and Push dev container images

on:
  pull_request:
  workflow_dispatch:
      image_registry:
        description: The container registry to push to (must be ghcr.io)
        default: "ghcr.io/sloretz"
        type: string
      image_name:
        description: The name of the image
        default: "ros-dev-container"
        type: string
  workflow_call:
    inputs:
      ros_distro:
        description: ROS Distro to build
        type: string
        required: true
      image_registry:
        description: The container registry to push to (must be ghcr.io)
        default: "ghcr.io/sloretz"
        type: string
      image_name:
        description: The name of the image
        default: "ros-dev-container"
        type: string

permissions:
      packages: write
      contents: read

jobs:

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be  # v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Install dependencies
        run: ./scripts/install_dependencies.bash

      - name: Log in to ghcr.io
        uses: Wandalen/wretry.action@62451a214c01d1b0136b4f87289d840b30d67b98  # v1.4.4
        with:
          attempt_limit: 3
          attempt_delay: 240000  # 4 minutes
          action: redhat-actions/podman-login@9184318aae1ee5034fbfbacc0388acf12669171f  # v1
          with: |
            username: ${{ github.actor }}
            password: ${{ github.token }}
            registry: ${{ inputs.image_registry }}

      - name: Dry Run
        id: dry-run
        run: |
          output=$(./scripts/build_dev_container_images.py \
            --registry "${{ inputs.image_registry }}" \
            --name "${{ inputs.image_name }}" \
            --push \
            --dry-run)
            echo "${output}"
          manifests=$(echo "${output}" | grep MANIFEST | awk '{print $2}' | sort | uniq | tr '\n' ' ')
          images=$(echo "${output}" | grep IMAGE | awk '{print $2}' | sort | uniq | tr '\n' ' ')
          echo "manifests=${manifests}" >> "${GITHUB_OUTPUT}"
          echo "images=${images}" >> "${GITHUB_OUTPUT}"

      - name: Build and Push Images
        run: |
          ./scripts/build_dev_container_images.py \
            --registry "${{ inputs.image_registry }}" \
            --name "${{ inputs.image_name }}" \
            --push

  # TODO Test step
  # call-test-pushed-images:
  #   needs: build-and-push
  #   uses: ./.github/workflows/test-pushed-dev-container-images.yaml
  #   with:
  #     ros_distro: ${{ inputs.ros_distro }}
  #     image_registry: ${{ inputs.image_registry }}
  #     image_name: ${{ inputs.image_name }}