name: CI AMD64 Dev Container (Ubuntu Jammy)

on:
  workflow_call:

jobs:
  ci-build-amd64-dev-image-jammy:
    name: CI AMD64 Dev Container (Ubuntu Jammy)
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203  # v1.0.13
        with:
          version: v0.8.0
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Build Image
        run: |
          earthly --ci +ros-dev-ubuntu-jammy
