name: CI Build AMD64 Images

on:
  pull_request

jobs:

  call-ci-build-humble:
    uses: ./.github/workflows/ci-build-amd64-image-one-ros-distro.yaml
    with:
      ros_distro: humble
  call-ci-build-jazzy:
    uses: ./.github/workflows/ci-build-amd64-image-one-ros-distro.yaml
    with:
      ros_distro: jazzy
  call-ci-build-kilted:
    uses: ./.github/workflows/ci-build-amd64-image-one-ros-distro.yaml
    with:
      ros_distro: kilted
  call-ci-build-rolling:
    uses: ./.github/workflows/ci-build-amd64-image-one-ros-distro.yaml
    with:
      ros_distro: rolling

  call-ci-build-dev-images:
    uses: ./.github/workflows/ci-build-amd64-dev-images.yaml
