name: CI Check test_images.py works

on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  call-ci-build-rolling:
    uses: ./.github/workflows/test-deployed-images-one-ros-distro.yaml
    with:
      ros_distro: rolling
