name: CI Lint GitHub Actions workflows
on:
  pull_request

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Download and run actionlint
        id: get_actionlint
        run: |
          # Download and verify actionlint binary
          set -e
          wget https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz
          echo '023070a287cd8cccd71515fedc843f1985bf96c436b7effaecce67290e7e0757  actionlint_1.7.7_linux_amd64.tar.gz' | sha256sum --check
          
          # Extract the binary
          tar -xzf actionlint_1.7.7_linux_amd64.tar.gz

          # Run the binary
          ./actionlint -color
        shell: bash
