name: ROS Humble Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'  # 00:00 on Sunday.

permissions:
      packages: write
      contents: read

jobs:
  build-and-deploy-humble:
    uses: ./.github/workflows/build-one-ros-distro.yaml
    with:
      ros_distro: humble
